# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Conversion
markdown:         redcarpet
highlighter:      pygments
excerpt_separator: <!--more-->

# Config for your profile.
title:            freytag.org.uk        # Site title
name:             Simon Freytag         # Your name
avatar:           /theme/img/avatar.jpg # Path to an avatar image

# I deploy the site under /pages on GAE, to keep Jekyll separate from other
# projects running on there. You'll probably want to set this to "/"
baseurl: "/pages"

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages", "_portfolio"]

# Turn the projects into a collection.
collections:
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html

defaults:
# Turn the profile sidebar on for all pages by default, except for _posts, where
# it is off (and is replaced by post-metadata). On individual pages, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: false
  -
    scope:
      path: "_projects"
    values:
      show_profile: false
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list


