# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Conversion
markdown:         redcarpet
highlighter:      pygments
excerpt_separator: <!--more-->

# Config for your profile.
title:            freytag.org.uk        # Site title
name:             Simon Freytag         # Your name
avatar:           /theme/img/avatar.jpg # Path to an avatar image

# I deploy the site under /pages on GAE, to keep Jekyll separate from other
# projects running on there. You'll probably want to set this to "/"
baseurl: "/pages"







