# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Conversion
markdown:         redcarpet
highlighter:      pygments
excerpt_separator: <!--more-->

# Config for your profile.
title:            friday-theme.github.io  # Site title
name:             John Smith              # Your name
avatar:           /theme/img/avatar.jpg   # Path to an avatar image

# I deploy the site under /pages on GAE, to keep Jekyll separate from other
# projects running on there. You'll probably want to set this to "/"
baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages", "_portfolio"]

# Turn the projects into a collection.
collections:
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html

defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: false
      layout: defaults/portfolio
  -
    scope:
      path: "_projects"
    values:
      show_profile: false
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list


